### ISSUE TITLE
Separating IDEAL and Boomerang

### ISSUE THREAD

**Issue by piskachev** [CROSSINGTUD/SPDS#70]
Currently, this repository contains both implementations for IDEAL and Boomerang using the push-down systems. There are applications where we only need one of both, and having the single build for both is just overhead in the dependencies. 
How about making a separation?

**Comment by johspaeth** [comment]
Instead of separating development of IDEAL and Boomerang, I suggest to refer to the artifacts on our nexus, i.e., add the following to your `pom.xml` 
```
<repository>
	<id>soot-release</id>
	<name>soot release</name>
	<url>https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/</url>
</repository>
```
and refer to the artifact as:
```
<dependency>
	<groupId>de.fraunhofer.iem</groupId>
	<artifactId>idealPDS</artifactId>
	<version>${version}</version>
</dependency>
```

**Comment by johspaeth** [comment]
Closed the issue, as I guess it solved the issue.
