### ISSUE TITLE
WPDS Document

### ISSUE THREAD

**Issue by niuzhi** [CROSSINGTUD/SPDS#88]
WPDS build and install,how to use?Can you provide detailed usage documentation?

**Comment by johspaeth** [comment]
Hi @niuzhi 
there are some initial examples to be found in [this directory](
https://github.com/CodeShield-Security/SPDS/tree/master/boomerangPDS/src/main/java/boomerang/example)

ExampleMain1.java present a minimal example for a BackwardQuery which computes the data-flow backward and computes the content (allocation site) of a variable at a statement.

ExampleMain2.java present a minimal example for a ForwardQuery which computes data-flow forward, and can be, for instance, be used to do a liveness analysis.

I hope that helps initially, do you have some further detailed question?
