### ISSUE TITLE
What happened to backwardSolveUnderScope in the CodeShield-Security fork?

### ISSUE THREAD

**Issue by copumpkin** [CROSSINGTUD/SPDS#92]
Apologies if this is the wrong place to ask, but I see that there's a much more recently updated fork of this repo [here](https://github.com/CodeShield-Security/SPDS) but it doesn't have issue tracking turned on. Since the contributors appear similar, I figured I'd ask here.

I'm wondering what happened to the [`backwardSolveUnderScope`](https://github.com/CROSSINGTUD/SPDS/blob/a768ea6f6405e21ffb4e7e6881783895395c4183/boomerangPDS/src/main/java/boomerang/WeightedBoomerang.java#L606) method in the newer fork. Is there a suggested replacement for it or is the feature gone?

**Comment by copumpkin** [comment]
It looks like it got deleted in [this commit](https://github.com/CodeShield-Security/SPDS/commit/01e2bf44e30e83b4511ce4bbe21a1292df827a23#diff-533634c8d4d1fd66d942948920e64009) but I'm not sure if that was temporary or if there's an intended replacement.

**Comment by johspaeth** [comment]
Hi @copumpkin,

thanks for the question, I just enabled the issue tracker in [this repository](https://github.com/CodeShield-Security/SPDS).

I removed the methods intentionally by the concept of a [query graph](https://github.com/CodeShield-Security/SPDS/blob/38c13cc6f093ecfe2d847a1aef06810b72b977dd/boomerangPDS/src/main/java/boomerang/QueryGraph.java#L31). The query graph is a data structure for all queries and their subqueries. Each subquery follows the scope/context of its parent query.

The query graph has a method [`addEdge`](
https://github.com/CodeShield-Security/SPDS/blob/38c13cc6f093ecfe2d847a1aef06810b72b977dd/boomerangPDS/src/main/java/boomerang/QueryGraph.java#L50) which can be used to guide a query, this is the replacement for `backwardSolveUnderScope`.

So `backwardQuery` should be the `child` argument to `addEdge`.

**Comment by copumpkin** [comment]
Oh nice, that graph looks neat! So if my workflow wants to be iteratively "bouncing" between Backward and Forward queries, and making sure I scope my Backward queries narrowly, does that query graph subsume all of that?

**Comment by johspaeth** [comment]
Exactly, this is the main idea behind the graph:

Allowing to "bounce" between queries and coordination of their scopes (= context = call stacks) in the way that child queries are allowed to propagate within the scopes of their parent queries. In that way one can reduce the amount of code that needs to analyzed.

**Comment by copumpkin** [comment]
@johspaeth is there an example of the graph in use? I see that backward results have a `getDataFlowPath` method on them which for a given FWQ returns a set of `Node` objects that I could use to add an edge, but what's the interpretation of that set?

Say I have the following logic:

1. BWQ from an interesting point in my program, which I don't want to scope because I want all allocation sites
2. FWQ from each of the allocation sites found in #1 
3. BWQ from each interesting program point found in #2, but I want these to be scoped only to paths from #2 so I don't step into a bunch of unrelated code to my original query. 

In step 3, with the `addEdge` API I need a `Node<Statement, Val>`. I could ask the backward results from #1 for `getDataFlowPath` for each FWQ it produces, but that gives me a set of nodes, and I'm unsure if it matters which element of that set I pick. If it does matter, is there a good way to pick?
